version: '3.8'

services:
  backend:
    build: .
    container_name: firmas_backend_container
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    networks:                # ðŸ‘ˆ AÃ±adimos la red externa
      - firma_net

networks:                    # ðŸ‘ˆ Declaramos la red externa
  firma_net:
    external: true
